FROM node:alpine

#USER node

#RUN mkdir -p /home/node/app
WORKDIR '/app'

#COPY --chown=node:node package.json .
COPY package.json .

RUN npm install

#COPY --chown=node:node ./ ./
COPY ./ ./

RUN chown -R node:node .
USER node

CMD ["npm", "run", "start"]